version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/gem"
    schedule:
      interval: "monthly"
    reviewers:
      - "Shopify/sorbet"
    labels:
      - "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "Shopify/sorbet"
    labels:
      - "dependencies"
